default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: '123456'

development:
  <<: *default
  database: msksj_development

test:
  <<: *default
  database: msksj_test

production:
  url: <%= ENV['DATABASE_URL'] %>